services:
  rag-api:
    build: .
    container_name: rag-api-service
    ports:
      - "8002:8002"
    networks:
      - rag-network-shared
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./documentos_oficiais:/app/documentos_oficiais
    restart: unless-stopped

networks:
  rag-network-shared:
    driver: bridge # Cria a rede automaticamente no notebook
